diff --git a/Makefile b/Makefile
index 88ded58..94cb200 100644
--- a/Makefile
+++ b/Makefile
@@ -18,7 +18,7 @@ ifeq ($(OS), Windows_NT)
     FPIC=
 else
     # let's assume "normal" UNIX such as linux
-    COMMON_LD_FLAGS=-ldl -lpthread -lz
+    COMMON_LD_FLAGS=-ldl -lpthread -lz -lpapihalide -lpapi -L /home/ppginf/rrlmachado/nobackup/repositories/libpapihalide -L /home/ppginf/rrlmachado/nobackup/repositories/papi/src
     FPIC=-fPIC
 ifeq ($(UNAME), Darwin)
     SHARED_EXT=dylib
@@ -435,6 +435,7 @@ SOURCE_FILES = \
   ParamMap.cpp \
   Parameter.cpp \
   PartitionLoops.cpp \
+  PAPIProfiling.cpp \
   Pipeline.cpp \
   Prefetch.cpp \
   PrintLoopNest.cpp \
@@ -607,6 +608,7 @@ HEADER_FILES = \
   ParamMap.h \
   Parameter.h \
   PartitionLoops.h \
+  PAPIProfiling.h \
   Pipeline.h \
   Prefetch.h \
   Profiling.h \
@@ -706,6 +708,7 @@ RUNTIME_CPP_COMPONENTS = \
   osx_host_cpu_count \
   osx_opengl_context \
   osx_yield \
+  papi_profiler \
   posix_allocator \
   posix_clock \
   posix_error_handler \
